### ISSUE TITLE
oneshot vienna/austria

### ISSUE THREAD

**Issue by kelkes** [oneshot/organizers#1]
Vienna needs more node.js-related events. I would like to organize the "oneshot vienna". We are a Vienna based node.js agency (www.trigo.at).

**Comment by gergelyke** [comment]
\o/

**Comment by mikeal** [comment]
@kelkes added you as an owner so that you can create a repo for austria :)

**Comment by mikeal** [comment]
don't forget to send a PR to the main website https://github.com/oneshot/oneshot.github.io

**Comment by kelkes** [comment]
thanks! we will start with the organization this week
