### ISSUE TITLE
one-shot Buenos Aires

### ISSUE THREAD

**Issue by bevacqua** [oneshot/organizers#2]
Hey there @mikeal, we talked at Gin.js about this, so I'm making an issue and see if we can make a one-shot happen in Buenos Aires.

I'll make sure to talk with the people you pointed me to. We are already organizing nodeschool/bots/beerjs in BA, but any other points are welcome as well : )

**Comment by mikeal** [comment]
I added you as an owner of the org. You can create a new repo here to organize the event and pull from the existing template. You can also use gh-pages to get a page up on nodeconf.com :)

**Comment by bevacqua** [comment]
Sweet. I actually just registered `nodeconf.com.ar`, and I was planning on following the `{year}.nodeconf.com.ar` pattern. Hope I'm able to have this thing take off! :rocket:

**Comment by mikeal** [comment]
That will still work, just set that in the CNAME and point the DNS to the same place :)

**Comment by a0viedo** [comment]
:+1:  let me know if you need help with anything

**Comment by mikeal** [comment]
don't forget to send a PR to the main website https://github.com/oneshot/oneshot.github.io

**Comment by a0viedo** [comment]
@mikeal @bevacqua  I think you guys forgot to create the [repo](https://github.com/oneshot/buenosaires)?

**Comment by bevacqua** [comment]
Created!
