### ISSUE TITLE
one shot Christchurch, New Zealand

### ISSUE THREAD

**Issue by digitalsadhu** [oneshot/organizers#3]
We are looking at running a one shot in late March 2015

georgewills
digitalsadhu
ebrobinson

Lets dooo this thang!

**Comment by gergelyke** [comment]
Nice! If you need any help/advice, ping @mikeal or me

**Comment by digitalsadhu** [comment]
Awesome thanks @gergelyke
We have things organized $$ wise and a venue locked down now. 

Need to create the oneshot/Christchurch repo and such next. Will you do that for us or do you give us permission to do that ourselves?

**Comment by gergelyke** [comment]
Invitation sent ;)

**Comment by digitalsadhu** [comment]
Cheers!

**Comment by mikeal** [comment]
don't forget to send a PR to the main website https://github.com/oneshot/oneshot.github.io

**Comment by digitalsadhu** [comment]
Will do!

**Comment by digitalsadhu** [comment]
PR sent!
