### ISSUE TITLE
second-shot Barcelona

### ISSUE THREAD

**Issue by PatrickHeneise** [oneshot/organizers#4]
After WeNode, we'd like to collaborate with nodeconf to make it better (not necessarily bigger).

**Comment by mikeal** [comment]
awesome, you have been added as an owner of this org, you can create a repo for your conference, pull from the cfp template, and use gh-pages to get a website up on nodeconf.com :)

**Comment by PatrickHeneise** [comment]
awesome, thanks! Will do a forward from wenode.barcelonajs.org later then.

**Comment by mikeal** [comment]
don't forget to send a PR to the main website https://github.com/oneshot/oneshot.github.io

**Comment by PatrickHeneise** [comment]
As soon as we have a date, will do
