### ISSUE TITLE
christchurch.nodeconf.com setup

### ISSUE THREAD

**Issue by digitalsadhu** [oneshot/organizers#5]
@mikeal @gergelyke 
I have pushed a base site to gh-pages for Christchurch and it is working at:
http://oneshot.nodeconf.com/christchurch/

I have added a CNAME file to gh-pages with `christchurch.nodeconf.com`

What needs to happen to get the site to show up at `http://christchurch.nodeconf.com` now?

**Comment by mikeal** [comment]
It already works :) http://christchurch.nodeconf.com/

There is already a wildcard for *.nodeconf.com to the gh-pages for this org :)

**Comment by digitalsadhu** [comment]
sweet!
