### ISSUE TITLE
One-Shot Austin

### ISSUE THREAD

**Issue by dcbartlett** [oneshot/organizers#6]
I'd like to become an organizer for One-Shot Austin.  It doesn't look like there is an one-shot for Austin, Texas yet, so i'd like to become the main organizer.  I'm a NodeJS consultant in the area and have expertise in many of the frameworks and libraries for node.  Now i'd like to have those great pieces of art shared with the rest of the community.  What better way than to hold a one-shot and bring in awesome speaks for the local community to help me.

If you guys would be so kind as to help me get started that would be awesome.

Regards,
Dennis Bartlett
NodeJS Consultant
512-584-3924
bartlett.dc.1@gmail.com
Austin, Tx

**Comment by mikeal** [comment]
Added you as an owner to the org, go ahead and setup your repo and send a PR for inclusion on the site :)

**Comment by dcbartlett** [comment]
@mikeal is there an email system with oneshot, or would i need to setup an email service if i wanted an email system?  onshot-austin.com or something?

Edit: Also, would we use the nodeconf.com (austin.nodeconf.com) or should i purchase a seperate domain?

**Comment by mikeal** [comment]
I think I can give you an email address @nodeconf.com :)

**Comment by dcbartlett** [comment]
Should i purchase a domain for the site?  Can i have a sub-domain?  i might actually setup both, just not sure which way would be best to portrait it.

I've started design for the austin site and should have some neat stuff soon to look at.

**Comment by mikeal** [comment]
you'll get a sub-domain "auto-magically" once you create a repo :) just use gh-pages and it should all work.

**Comment by dcbartlett** [comment]
cool.

**Comment by dcbartlett** [comment]
hum, interestingly, i copied the template into https://github.com/oneshot/austin and it has a gh-pages repo, but http://austin.nodeconf.com/ does not seem to work.  Maybe i did something wrong?

**Comment by dcbartlett** [comment]
i did notice that http://oneshot.nodeconf.com/austin/ is working though.

**Comment by dcbartlett** [comment]
I got the url working properly now.  @mikeal if you can toss me an email address or something please let me know at my email (bartlett.dc.1@gmail.com)

Thanks!!!
