### ISSUE TITLE
Whats the policy on using the logo and any prizes/drawing for one-shot events?

### ISSUE THREAD

**Issue by dcbartlett** [oneshot/organizers#7]
I'd like to have a few door-prizes at our one-shot and i'm wanting to find out what the policy is around using the one-shot logo.

Here is an example of how i'd like to use it.

https://www.dropbox.com/s/2o6xmu2vgo47kc5/Screenshot%202015-02-02%2022.33.33.png?dl=0

**Comment by mikeal** [comment]
Looks awesome, use the logo however you'd like :)

**Comment by dcbartlett** [comment]
And with that, i close this :D
