### ISSUE TITLE
Nodeconf in Santa Cruz

### ISSUE THREAD

**Issue by jeffmarsh** [oneshot/organizers#9]
## Nodeconf Santa Cruz, California

We are interested in hosting a nodeconf this summer at the beach (well maybe not ON the beach). The list of organizers is:
- jeffmarsh@mac.com
- jeffreypriebe@gmail.com
- albertwchang@gmail.com
- anthony@chovy.com

**Comment by mikeal** [comment]
awesome! I need all the github handles in order to add people :)

**Comment by jeffreypriebe** [comment]
jeffmarsh
jeffreypriebe
albertwchang
chovy

**Comment by mikeal** [comment]
Awesome, all setup now. Repo is there, team is there, you're all invited. The guide should help you get the rest of the way through your event ;) https://github.com/oneshot/organizers/wiki

**Comment by jeffreypriebe** [comment]
Thanks for getting this going.

**Comment by jeffmarsh** [comment]
No worries. I just really wanted to do it.
